### PR TITLE
remove science support for noresm2.1 release

### PR DESCRIPTION
**Pull request by mvertens**
### Description of changes
remove science support  tags for noresm2.1 release from config_compsets.xml

### Specific notes

Contributors other than yourself, if any:

CTSM Issues Fixed:

Are answers expected to change (and if so in what way)? No

Any User Interface Changes (namelist or namelist defaults changes)? No

Testing performed, if any: None

### CODE REVIEW

**Comment by mvertens** [comment]
@mvdebolskiy - if you could look at this today it would be really helpful. We are trying to assemble the final release tag today if possible.

**Comment by mvdebolskiy** [comment]
Looks ok to me. The only caviat is that people will have to add `--run-unsupported` in their scripts?

**Comment by mvertens** [comment]
@mvdebolskiy - yes they will now need to add --run-unsupported.

**Comment by mvdebolskiy** [comment]
Is the branch you are merging this correct? 2.1 will point to [NorESMhub:release-clm5.0.14-Nor](https://github.com/NorESMhub/CTSM/tree/release-clm5.0.14-Nor) and not some new branch?

**Comment by mvertens** [comment]
Yes.

**Comment by mvertens** [comment]
@mvdebolskiy - are you you okay with this PR? If so - can you please finish reviewing it.

**Review by mvdebolskiy — APPROVED** [review]

**Comment by mvertens** [comment]
@mvdebolskiy - thanks!

**Comment by mvertens** [comment]
This was tagged as release-clm5.0.14-Nor_v1.0.5

**Pull request merged**
