### PR TITLE
Megan CTSM

### PR DESCRIPTION
**Pull request by rosiealice**
### Description of changes
Megan changes without the fire emissions commits.

### Specific notes
Same notes as the previous now closed PR 
https://github.com/NorESMhub/CTSM/pull/74

Contributors other than yourself, if any:

CTSM Issues Fixed (include github issue #):
https://github.com/NorESMhub/CTSM/issues/36

Are answers expected to change (and if so in what way)?
Yes, all the MEG_* fields will change, but nothing else. 

Any User Interface Changes (namelist or namelist defaults changes)?
No

Does this create a need to change or add documentation? Did you do so?
Yes, but haven;'t changed yet pending further coupled model testing. 

Testing performed, if any:
(List what testing you did to show your changes worked as expected)
(This can be manual testing or running of the different test suites)
(Documentation on system testing is here: https://github.com/ESCOMP/ctsm/wiki/System-Testing-Guide)
(aux_clm on derecho for intel/gnu and izumi for intel/gnu/nag/nvhpc is the standard for tags on master)

**NOTE: Be sure to check your coding style against the standard
(https://github.com/ESCOMP/ctsm/wiki/CTSM-coding-guidelines) and review
the list of common problems to watch out for
(https://github.com/ESCOMP/CTSM/wiki/List-of-common-problems).**

### CODE REVIEW

**Comment by mvertens** [comment]
@rosiealice - I started running a test suite and have encountered problems. Here are the first two:
I'm seeing 
 ```
ENDRUN:
 ERROR:
 clmfates_interface::ReadParametereadNcdio:: - Error reading.  Var:fates_turnover_leaf_canopy
```
In the following tests
```
ERP_D.f19_g17.2000_DATM%GSWP3v1_CLM60%FATES_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesCold
ERP_Ld30.f45_f45_mg37.2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesColdSatPhen
ERS_D_Ld5.5x5_amazon.2000_DATM%GSWP3v1_CLM60%FATES_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesCold
SMS.ne30pg3_ne30pg3_mtn14.2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesColdSatPhen
SMS_D.1x1_brazil.2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesColdDryDepSatPhen
SMS_D.ne30pg3_ne30pg3_mtn14.2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesColdDryDepSatPhen
SMS_D.ne30pg3_ne30pg3_mtn14.2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesColdMeganSatPhen
SMS_D_Ld3.ne30pg3_ne30pg3_mtn14.2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesColdSatPhen_prescribed
```

I also got the following error in the test creation
ERROR: Command: /cluster/work/users/mvertens/noresm/ERS_Lm25.f45_f45_mg37.2000_DATM%GSWP3v1_CLM60%FATES-NOCOMP_SICE_SOCN_MOSART_SGLC_SWAV.betzy_intel.clmFatesColdTwoStreamNoCompFixedBioGeo.G.baseline2507
can't open file `/cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07/src/fates/parameter_files/fates_params_default.cdl` for reading:
        No such file or directory

I fixed this problem by putting in logic in testmods to determine the correct $FATESDIR - but now I get the failure

          File "/cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_rosie/components/clm/src/fates/tools/modify_fates_paramfile.py", line 26, in <module>>
            import numpy as np
        ModuleNotFoundError: No module named 'numpy'' from dir '/cluster/work/users/mvertens/noresm/ERS_Lm25.f45_f45_mg37.2000_DATM%GSWP3v1_CLM60%FATES-NOCOMP_SICE_SOCN_MOSART_SGLC_SWAV.betzy_intel.clm-FatesColdTwoStreamNoCompFixedBioGeo.G.20241113_115331_op9u4e'



The reason for the above file error is that I am running these tests out of a noresm checkout rather than out of a ctsm checkout! so the file structure is different. I can try running out of a ctsm checkout instead.

**Comment by rosiealice** [comment]
Just cheking this out now @mvertens . Will get back to you in a bit.

**Comment by mvertens** [comment]
Thanks @rosiealice. It also looks like the latest version of CIME does not permit you to do any tests with month bounds (i.e. _LmXX in the test name). We are using close to latest version of CIME in noresm2_5_alpha07 - whereas CTSM is using a version that is 6 months old. So I will change our tests for aux_clm_noresm to make sure we have no month specification in the test names.

**Comment by rosiealice** [comment]
So, the model is trying to find the '**fates_turnover_leaf_canopy**' variable in the parameter file. This is a quite recently introduced parameter, and so I would not be surprised if the cause was that we were using the wrong default fates_paramfile. 

- One curious thing is the code in alpha07 already seems to point to a version of FATES with this parameter, so it is a bit strange that any of these runs go 'out ot the box' without needing to make a new parameter file in the first place.
https://github.com/NorESMhub/fates/blob/e96f09e5f7aa156d350871c26f272c57edf9f7af/parameter_files/fates_params_default.cdl#L660C9-L660C35

**  In addition**  to this parameter, the MEGAN code also introduces new parameters. 
* https://github.com/rosiealice/fates/blob/63021eae385ffcd8b2f80f8bf7f3ab44591fd1ca/parameter_files/fates_params_default.cdl#L677C9-L677C27
and I suspect that the test would fail later on when it wanted to read those as well.

The solution to both of these is broadly to run with the parameter file that goes with this code which is here:
**/cluster/work/users/rosief/git/NorESM_MEGAN_test/components/clm/src/fates/parameter_files/fates_params_default_megan.nc**

How to integrate the parameter file in the tests is not clear to me. How does that normally work when you test a branch that needs a new parameter file?  I guess this is something to do with the rest of the errors: 
**_07/shell_commands' failed with error 'can't open file /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07/src/fates/parameter_files/fates_params_default.cdl for reading:_**
which seem to be trying to do the automatic file generation thing (FATES stores its parameter files as a .cdl and then makes the netcdf files 'on the fly) that we were talking about with @mvdebolskiy the other day (and which he potentially correctly asserted would be annoying on account of their need for NCO modules, (or similar). But here it seems like the actual problem is with the fact that it can't find the parameter file in the path "**/cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07/src/fates/parameter_files/fates_params_default.cdl**". To ask an obvious question, is the file there?

**Comment by rosiealice** [comment]
I guess I was going to add, is it worth 'testing' the default version of the code first to troubleshoot these types of things?

**Comment by mvertens** [comment]
I agree. I can try to fire off a test with the default version. Are you referring to the latest version on master?

**Comment by rosiealice** [comment]
The version I used is the one linked from the alpha07 tag. So probably best to use that? 

It was this CTSM
https://github.com/NorESMhub/CTSM/tree/ctsm5.3.0-noresm_v0

and this FATES
https://github.com/NGEET/fatessci.1.78.2_api.36.0.0

**Comment by mvertens** [comment]
@rosiealice - the problem seems to be that in lnd_in we are trying to read in 
fates_paramfile = '/cluster/shared/noresm/inputdata/lnd/clm2/paramdata/fates_params_api.36.0.0_12pft_c240517.nc'. 
And the same holds for the head of the ctsm noresm branch.

Since `the fates branch you are pointing to is off of sci.1.78.3_api.36.1.0` (doing this from a git log on your branch).
The fates_paramfile is set in namelist_files/namelist_defaults_ctsm.xml. So to get your parameter file - all we have to do (I think) is simply modify this setting. @mvdebolskiy - do you agree with that?

**Comment by rosiealice** [comment]
Sounds about right @mvertens. Hopefully changing the setting will work. I wonder how we normally test things that need new parameter defaults?

**Comment by glemieux** [comment]
> Sounds about right @mvertens. Hopefully changing the setting will work. I wonder how we normally test things that need new parameter defaults?

If I understand the question, when we have non-default parameter file values that need to be routinely tested, we use the on-the-fly netcdf generation scheme that you mentioned above.  There is a PR that is 'stuck' to try and make this a little more robust, but we need to get back to it now that some upstream issues have been addressed: https://github.com/ESCOMP/CTSM/pull/2336.

I should note that alternate ways of generating and storing the files for testing has also been discussed over on the elm side of things: https://github.com/E3SM-Project/E3SM/pull/6639#issuecomment-2407983790

**Comment by mvertens** [comment]
@glemieux - thanks for the clarification. That is super helpful.

Just to clarify - this is a parameter file that will need to accompany this PR - and not one that just needs to be routinely tested. So my understanding would be that we actually need to do the following:
- copy `/cluster/work/users/rosief/git/NorESM_MEGAN_test/components/clm/src/fates/parameter_files/fates_params_default_megan.nc` in the standard CTSM inputdata with a new name
- point to the above new param dataset in the` namelist_defaults_ctsm.xml` file entry for `fates_paramfile`
Does that make sense?

**Comment by mvertens** [comment]
@rosiealice - what I have done is
- create a personal CTSM branch from your branch in this PR
- update this branch to ctsm5.3.11 
- add additional modifications in cime_config and bld that are needed for new noresm testing as well as compatibility for FATES to use megan. 
- start the testing again 
I'll keep you posted on the results.

**Comment by mvertens** [comment]
@mvdebolskiy - I cannot create a case with a stand-alone checkout of ctsm-noresm. I get the following error:
Batch_system_type is slurm
job is case.run USER_REQUESTED_WALLTIME None USER_REQUESTED_QUEUE None WALLTIME_FORMAT %H:%M:%S
WARNING: No queue on this system met the requirements for this job. Falling back to defaults
ERROR: No queues found
I am trying the following command:
./create_newcase --case foo --compset 2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV --res ne30pg3_ne30pg3_mtn14 --project nn9039k --run-unsupported --mach betzy
I have updated all of the externals in ctsm to be the same as in noresm2_5_alpha07.

**Comment by glemieux** [comment]
> Just to clarify - this is a parameter file that will need to accompany this PR - and not one that just needs to be routinely tested. So my understanding would be that we actually need to do the following:
> 
> * copy `/cluster/work/users/rosief/git/NorESM_MEGAN_test/components/clm/src/fates/parameter_files/fates_params_default_megan.nc` in the standard CTSM inputdata with a new name
> * point to the above new param dataset in the` namelist_defaults_ctsm.xml` file entry for `fates_paramfile`
>   Does that make sense?

Gotcha, thanks for the clarification.  What you've laid out is equivalent to what we do as well.

**Comment by mvertens** [comment]
@rosiealice - it turns out that we need this PR for noresm2_5_alpha08. What I found out today is the following:
- running the test - SMS_D_Ld1.ne30pg3_tn14.N1850fates-sp.betzy_intel.allactive-defaultio - caused a crash in VOCEmissionMod.F90. Previously we were turning off megan in this test. With megan on, it does not work. Removing the debug flag caused the test to pass. 
- using the code for this PR along with some cime_config/ and bld/ modifications from me - SMS_D_Ld1.ne30pg3_tn14.N1850fates-sp.betzy_intel.allactive-defaultio  passes. 
- What I want to do is the following:
  -  accept your FATES PR
  - do a PR to your branch with my changes
  - then accept this PR and use that as the ctsm tag in noresm2_5_alpha08 There are still issues with some of the stand-alone tests - but most of the tests are now passing and the key test needed for alpha08 is fine.

**Comment by mvertens** [comment]
@rosiealice - it turns out that it will be much easier for me to close this PR and issue a new one with my changes on top of yours as well (which had some more relative to what you merged last week). I'll copy the PR summary exactly as you have it here. First I need to do some additional testing then I'll issue the PR again and have both you and @mvdebolskiy review it.
There should not be that many files since I just made a PR that had updated the noresm branch to ctsm5.3.011 - and these changes should be on top of that.

**Comment by rosiealice** [comment]
OK thanks @mvertens  Let me know if I can help out at all...

**Comment by mvertens** [comment]
Closing in favor of #99

**Comment by mvertens** [comment]
closing in favor of #99

**Pull request closed without merging**
