### PR TITLE
Fix apply_use_init_interp() use in branch run

### PR DESCRIPTION
**Pull request by blcc**
Fix issue of 
https://github.com/ESCOMP/CTSM/issues/786

### CODE REVIEW

**Comment by blcc** [comment]
Hi, it is a very small modification to allow branch run in CLM. Which is fixed in upstream.
It would be great if it can be merged.

**Comment by blcc** [comment]
Need be fix with present NorESM tags.

**Comment by blcc** [comment]
Test OK.

**Comment by huitang-earth** [comment]
@blcc You are not supposed to send pull request to the master branch of CTSM. Please find the correct branch for merging the changes. @MichaelSchulzMETNO @DirkOlivie  You might suggest which branch this change should go to?

**Comment by blcc** [comment]
Wrong branch.

**Pull request closed without merging**
