### PR TITLE
add MEGAN compatibility with FATES

### LINKED ISSUE #91: Running new noresm testlist on betzy
### Brief summary of bug
Using noresm2_5_alpha06 with a new proposed CLM test suite for noresm - I am getting errors like the following in numerous FATES tests:

```
  Case dir: /cluster/home/mvertens/noresm/ctsm_testing/ERP_D_Ld10_P64x2.f10_f10_mg37.IHistClm60BgcCrop.betzy_intel.clm-default.20241014_144301_kznjgk
    Errors were:
        Building test for ERP in directory /cluster/work/users/mvertens/noresm/ctsm_testing/ERP_D_Ld10_P64x2.f10_f10_mg37.IHistClm60BgcCrop.betzy_intel.clm-default.20241014_144301_kznjgk
        NOTE: LND_TUNING_MODE is clm6_0_GSWP3v1 which is NOT tuned, but is based on clm5_0_GSWP3v1
        NOTE: LND_TUNING_MODE is clm6_0_GSWP3v1 which is NOT tuned, but is based on clm5_0_GSWP3v1
        /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_v1/components/clm/src/utils/clmfates_interfaceMod.F90(890): error #6460: This is not a component name that is defined in the encompassing structure.   [PFT_AREAFRAC_LU]

        /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_v1/components/clm/src/utils/clmfates_interfaceMod.F90(890): error #6366: The shapes of the array expressions do not conform.

        /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_v1/components/clm/src/utils/clmfates_interfaceMod.F90(891): error #6460: This is not a component name that is defined in the encompassing structure.   [BAREGROUNDFRAC]

        /cluster/projects/nn10013k/mvertens/src/noresm2_5_alpha07_v1/components/clm/src/utils/clmfates_interfaceMod.F90(2021): error #6460: This is not a component name that is defined in the encompassing structure.   [FLUSH_ALL_HVARS]

        ERROR: BUILD FAIL: clm.buildlib failed, cat /cluster/home/mvertens/noresm/ctsm_testing/ERP_D_Ld10_P64x2.f10_f10_mg37.IHistClm60BgcCrop.betzy_intel.clm-default.20241014_144301_kznjgk/bld/lnd.bldlog.241014-145702
```

### LINKED ISSUE #94: Update CTSM to latest ESCOMP/master and update externals.
- [x] merge ESCOMP/CTSM/master
- [x] update ccs_config
- [x] update cime?
- [x] update share, cmeps, cdeps ...

### PR DESCRIPTION
**Pull request by mvertens**
### Description of changes
- Megan changes without the fire emissions commits.
- updated testlist for aux_noresm_clm
- removal of ctsm5.1
- updates of submodules to be consistent with upcoming noresm2_5_alpha08 tag

### Specific notes
Same notes as the previous now closed PR 
https://github.com/NorESMhub/CTSM/pull/74

Contributors other than yourself, if any: @rosiealice (the primary developer of these changes)

CTSM Issues Fixed (include github issue #):
https://github.com/NorESMhub/CTSM/issues/36

Are answers expected to change (and if so in what way)?
Yes, all the MEG_* fields will change, but nothing else. 

Any User Interface Changes (namelist or namelist defaults changes)?
No

Does this create a need to change or add documentation? Did you do so?
Yes, but haven;'t changed yet pending further coupled model testing. 

Testing performed, if any:
Ran the following test command:
./create_test --xml-category aux_clm_noresm --xml-machine betzy --baseline-root ~/baselines/ctsm_develop --generate noresm2_5_alpha08 --test-id ctsmpr1 --project nn9039k -o

```
    FAIL ERS_Ld761.ne30pg3_ne30pg3_mtn14.2000_DATM%GSWP3v1_CLM60%FATES-NOCOMP_SICE_SOCN_MOSART_SGLC_SWAV.betzy_intel.clm-FatesColdNoComp RUN time=2995
    FAIL SMS_D.1x1_brazil.2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesColdDryDepSatPhen RUN time=56
    FAIL SMS_D_Ld3.ne30pg3_ne30pg3_mtn14.2000_DATM%GSWP3v1_CLM60%FATES-SP_SICE_SOCN_SROF_SGLC_SWAV.betzy_intel.clm-FatesColdSatPhen_prescribed RUN time=62
```
All the other tests passed.

### CODE REVIEW

**Comment by mvdebolskiy** [comment]
Ok. I've pushed some changes to make things clearer.

**Comment by mvertens** [comment]
Did you test to see if the answers were bfb - both with non-fates and fates?

**Comment by mvdebolskiy** [comment]
No, not yet. I wanted to look at the fates side tomorrow. Can you try to tests this?

**Comment by mvertens** [comment]
I'm concerned about your changes. This code was vetted closely and worked. You are putting in an optimization that would be fine for a second stage - but this is holding up simulations and could come in as a secondary phase. The key priority right now is to have the next simulation done.

**Review by rosiealice — APPROVED** [review]
Changes approved in CTSM meeting.

**Pull request merged**
